### ISSUE TITLE
Last blockquote does not render with attribution

### ISSUE THREAD

**Issue by paulathevalley** [dweidner/markdown-it-attribution#4]
In a markdown file with as many blockquotes as paragraphs, the fifth blockquote does **not** render with an attribution.

Expected:
```html
<figure class="blockquote">
<blockquote>
<p>blockquote 5</p>
</blockquote>
<figcaption class="blockquote-attribution">citation 5</figcaption>
</figure>
```

Actual:
```html
<blockquote>
<p>blockquote 5
~ citation 5</p>
</blockquote>
```

See example here: https://codesandbox.io/s/busy-tesla-b8lk4?file=/src/App.js

I believe I found the offending line: https://github.com/dweidner/markdown-it-attribution/blob/master/index.js#L259 
```for (var i = 0, l = tokens.length; i < l; i++) {```

In this example, `l = tokens.length` does not update in the `for` loop. It stays at `40`, which is the initial state of `tokens` I'm guessing, and the last blockquote token starts at `52`. If you add four more paragraphs to the example markdown file in the above codesandbox link, you can see the fifth blockquote token renders correctly. 

I don't know enough about what `state.tokens` is doing to suggest the best fix. If the variable assignment is removed entirely from the `for` loop, it works as expected: `for (var i = 0; i < state.tokens.length; i++) {`, but I’m not sure if this is the best idea. 

ok thanks for making an accessible attribution plugin!!!

**Comment by dweidner** [comment]
Interesting find. Thank you for the sandbox project. I will have a look into the issue.

**Comment by dweidner** [comment]
Your are absolutely right, we are inserting four new tokens (`<figure>`, `</figure>`, `<figcaption>`, `</figcaption>`) into the token stream, but are not updating the variable holding the total length of the stream. I prepared an update and will publish a new release. Thank you again for your detailed error report.
